// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Addresses           string
	CartItems           string
	FlywaySchemaHistory string
	Ingredients         string
	Orders              string
	RecipeIngredients   string
	Recipes             string
	UserAddresses       string
	Users               string
}{
	Addresses:           "addresses",
	CartItems:           "cart_items",
	FlywaySchemaHistory: "flyway_schema_history",
	Ingredients:         "ingredients",
	Orders:              "orders",
	RecipeIngredients:   "recipe_ingredients",
	Recipes:             "recipes",
	UserAddresses:       "user_addresses",
	Users:               "users",
}
