// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Addresses", testAddressesUpsert)

	t.Run("CartItems", testCartItemsUpsert)

	t.Run("FlywaySchemaHistories", testFlywaySchemaHistoriesUpsert)

	t.Run("Ingredients", testIngredientsUpsert)

	t.Run("Orders", testOrdersUpsert)

	t.Run("RecipeIngredients", testRecipeIngredientsUpsert)

	t.Run("Recipes", testRecipesUpsert)

	t.Run("UserAddresses", testUserAddressesUpsert)

	t.Run("Users", testUsersUpsert)
}
