// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testRecipeIngredients(t *testing.T) {
	t.Parallel()

	query := RecipeIngredients()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testRecipeIngredientsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecipeIngredient{}
	if err = randomize.Struct(seed, o, recipeIngredientDBTypes, true, recipeIngredientColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeIngredient struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := RecipeIngredients().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRecipeIngredientsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecipeIngredient{}
	if err = randomize.Struct(seed, o, recipeIngredientDBTypes, true, recipeIngredientColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeIngredient struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := RecipeIngredients().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := RecipeIngredients().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRecipeIngredientsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecipeIngredient{}
	if err = randomize.Struct(seed, o, recipeIngredientDBTypes, true, recipeIngredientColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeIngredient struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RecipeIngredientSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := RecipeIngredients().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRecipeIngredientsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecipeIngredient{}
	if err = randomize.Struct(seed, o, recipeIngredientDBTypes, true, recipeIngredientColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeIngredient struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := RecipeIngredientExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if RecipeIngredient exists: %s", err)
	}
	if !e {
		t.Errorf("Expected RecipeIngredientExists to return true, but got false.")
	}
}

func testRecipeIngredientsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecipeIngredient{}
	if err = randomize.Struct(seed, o, recipeIngredientDBTypes, true, recipeIngredientColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeIngredient struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	recipeIngredientFound, err := FindRecipeIngredient(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if recipeIngredientFound == nil {
		t.Error("want a record, got nil")
	}
}

func testRecipeIngredientsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecipeIngredient{}
	if err = randomize.Struct(seed, o, recipeIngredientDBTypes, true, recipeIngredientColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeIngredient struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = RecipeIngredients().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testRecipeIngredientsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecipeIngredient{}
	if err = randomize.Struct(seed, o, recipeIngredientDBTypes, true, recipeIngredientColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeIngredient struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := RecipeIngredients().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testRecipeIngredientsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	recipeIngredientOne := &RecipeIngredient{}
	recipeIngredientTwo := &RecipeIngredient{}
	if err = randomize.Struct(seed, recipeIngredientOne, recipeIngredientDBTypes, false, recipeIngredientColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeIngredient struct: %s", err)
	}
	if err = randomize.Struct(seed, recipeIngredientTwo, recipeIngredientDBTypes, false, recipeIngredientColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeIngredient struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = recipeIngredientOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = recipeIngredientTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := RecipeIngredients().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testRecipeIngredientsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	recipeIngredientOne := &RecipeIngredient{}
	recipeIngredientTwo := &RecipeIngredient{}
	if err = randomize.Struct(seed, recipeIngredientOne, recipeIngredientDBTypes, false, recipeIngredientColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeIngredient struct: %s", err)
	}
	if err = randomize.Struct(seed, recipeIngredientTwo, recipeIngredientDBTypes, false, recipeIngredientColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeIngredient struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = recipeIngredientOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = recipeIngredientTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RecipeIngredients().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func recipeIngredientBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *RecipeIngredient) error {
	*o = RecipeIngredient{}
	return nil
}

func recipeIngredientAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *RecipeIngredient) error {
	*o = RecipeIngredient{}
	return nil
}

func recipeIngredientAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *RecipeIngredient) error {
	*o = RecipeIngredient{}
	return nil
}

func recipeIngredientBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *RecipeIngredient) error {
	*o = RecipeIngredient{}
	return nil
}

func recipeIngredientAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *RecipeIngredient) error {
	*o = RecipeIngredient{}
	return nil
}

func recipeIngredientBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *RecipeIngredient) error {
	*o = RecipeIngredient{}
	return nil
}

func recipeIngredientAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *RecipeIngredient) error {
	*o = RecipeIngredient{}
	return nil
}

func recipeIngredientBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *RecipeIngredient) error {
	*o = RecipeIngredient{}
	return nil
}

func recipeIngredientAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *RecipeIngredient) error {
	*o = RecipeIngredient{}
	return nil
}

func testRecipeIngredientsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &RecipeIngredient{}
	o := &RecipeIngredient{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, recipeIngredientDBTypes, false); err != nil {
		t.Errorf("Unable to randomize RecipeIngredient object: %s", err)
	}

	AddRecipeIngredientHook(boil.BeforeInsertHook, recipeIngredientBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	recipeIngredientBeforeInsertHooks = []RecipeIngredientHook{}

	AddRecipeIngredientHook(boil.AfterInsertHook, recipeIngredientAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	recipeIngredientAfterInsertHooks = []RecipeIngredientHook{}

	AddRecipeIngredientHook(boil.AfterSelectHook, recipeIngredientAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	recipeIngredientAfterSelectHooks = []RecipeIngredientHook{}

	AddRecipeIngredientHook(boil.BeforeUpdateHook, recipeIngredientBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	recipeIngredientBeforeUpdateHooks = []RecipeIngredientHook{}

	AddRecipeIngredientHook(boil.AfterUpdateHook, recipeIngredientAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	recipeIngredientAfterUpdateHooks = []RecipeIngredientHook{}

	AddRecipeIngredientHook(boil.BeforeDeleteHook, recipeIngredientBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	recipeIngredientBeforeDeleteHooks = []RecipeIngredientHook{}

	AddRecipeIngredientHook(boil.AfterDeleteHook, recipeIngredientAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	recipeIngredientAfterDeleteHooks = []RecipeIngredientHook{}

	AddRecipeIngredientHook(boil.BeforeUpsertHook, recipeIngredientBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	recipeIngredientBeforeUpsertHooks = []RecipeIngredientHook{}

	AddRecipeIngredientHook(boil.AfterUpsertHook, recipeIngredientAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	recipeIngredientAfterUpsertHooks = []RecipeIngredientHook{}
}

func testRecipeIngredientsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecipeIngredient{}
	if err = randomize.Struct(seed, o, recipeIngredientDBTypes, true, recipeIngredientColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeIngredient struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RecipeIngredients().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRecipeIngredientsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecipeIngredient{}
	if err = randomize.Struct(seed, o, recipeIngredientDBTypes, true); err != nil {
		t.Errorf("Unable to randomize RecipeIngredient struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(recipeIngredientColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := RecipeIngredients().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRecipeIngredientsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecipeIngredient{}
	if err = randomize.Struct(seed, o, recipeIngredientDBTypes, true, recipeIngredientColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeIngredient struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testRecipeIngredientsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecipeIngredient{}
	if err = randomize.Struct(seed, o, recipeIngredientDBTypes, true, recipeIngredientColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeIngredient struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RecipeIngredientSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testRecipeIngredientsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RecipeIngredient{}
	if err = randomize.Struct(seed, o, recipeIngredientDBTypes, true, recipeIngredientColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeIngredient struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := RecipeIngredients().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	recipeIngredientDBTypes = map[string]string{`ID`: `int`, `RecipeID`: `int`, `IngredientID`: `int`}
	_                       = bytes.MinRead
)

func testRecipeIngredientsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(recipeIngredientPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(recipeIngredientAllColumns) == len(recipeIngredientPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &RecipeIngredient{}
	if err = randomize.Struct(seed, o, recipeIngredientDBTypes, true, recipeIngredientColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeIngredient struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RecipeIngredients().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, recipeIngredientDBTypes, true, recipeIngredientPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize RecipeIngredient struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testRecipeIngredientsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(recipeIngredientAllColumns) == len(recipeIngredientPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &RecipeIngredient{}
	if err = randomize.Struct(seed, o, recipeIngredientDBTypes, true, recipeIngredientColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RecipeIngredient struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RecipeIngredients().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, recipeIngredientDBTypes, true, recipeIngredientPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize RecipeIngredient struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(recipeIngredientAllColumns, recipeIngredientPrimaryKeyColumns) {
		fields = recipeIngredientAllColumns
	} else {
		fields = strmangle.SetComplement(
			recipeIngredientAllColumns,
			recipeIngredientPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := RecipeIngredientSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testRecipeIngredientsUpsert(t *testing.T) {
	t.Parallel()

	if len(recipeIngredientAllColumns) == len(recipeIngredientPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLRecipeIngredientUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := RecipeIngredient{}
	if err = randomize.Struct(seed, &o, recipeIngredientDBTypes, false); err != nil {
		t.Errorf("Unable to randomize RecipeIngredient struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert RecipeIngredient: %s", err)
	}

	count, err := RecipeIngredients().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, recipeIngredientDBTypes, false, recipeIngredientPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize RecipeIngredient struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert RecipeIngredient: %s", err)
	}

	count, err = RecipeIngredients().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
